export const equipmentMonitoringConfig = {
  water: { name: '水处理', type: 'grouped', groups: [
    { id: 'mon_w_phys', label: '综合指标-理化指标', items: [{v:'water_temp',l:'水温'},{v:'color',l:'色度'},{v:'odor',l:'臭'},{v:'turbidity',l:'浊度'},{v:'transparency',l:'透明度'},{v:'ph',l:'pH'},{v:'residue',l:'残渣'},{v:'mineralization',l:'矿化度'},{v:'conductivity',l:'电导率'},{v:'redox',l:'氧化还原电位'},{v:'acidity',l:'酸度'},{v:'alkalinity',l:'碱度'},{v:'co2',l:'二氧化碳'}], extras:[{v:'mon_w_phys_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_w_anion', label: '综合指标-无机阴离子', items: [{v:'sulfide',l:'硫化物'},{v:'cyanide',l:'氰化物'},{v:'sulfate',l:'硫酸盐'},{v:'boron',l:'硼'},{v:'chlorine_free',l:'游离氯和总氯'},{v:'chloride',l:'氯化物'},{v:'fluoride',l:'氟化物'},{v:'iodide',l:'碘化物'}] },
    { id: 'mon_w_nutrient', label: '综合指标-营养盐及有机污染综合指标', items: [{v:'do',l:'溶解氧'},{v:'cod',l:'化学需氧量'},{v:'codmn',l:'高锰酸盐指数'},{v:'bod',l:'生化需氧量'},{v:'toc',l:'总有机碳'},{v:'p_element',l:'元素磷'},{v:'phosphorus',l:'磷'},{v:'kjeldahl_n',l:'凯氏氮'},{v:'tn',l:'总氮'},{v:'no3n',l:'硝酸盐氮'},{v:'no2n',l:'亚硝酸盐氮'},{v:'nh3n',l:'氨氮'}], extras:[{v:'mon_w_nutr_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_w_metal', label: '综合指标-金属及其化合物', items: [{v:'ag',l:'银'},{v:'al',l:'铝'},{v:'as',l:'砷'},{v:'ba',l:'钡'},{v:'be',l:'铍'},{v:'bi',l:'铋'},{v:'cd',l:'镉'},{v:'co',l:'钴'},{v:'cr',l:'铬'},{v:'cu',l:'铜'},{v:'hg',l:'汞'},{v:'fe',l:'铁'},{v:'mn',l:'锰'},{v:'ni',l:'镍'},{v:'mo',l:'钼'},{v:'pb',l:'铅'},{v:'sb',l:'锑'},{v:'se',l:'硒'},{v:'zn',l:'锌'},{v:'v',l:'钒'},{v:'in_tl',l:'铟和铊'},{v:'th',l:'钍'},{v:'u',l:'铀'},{v:'k_na',l:'钾和钠'},{v:'ca_mg',l:'钙、镁（含总硬度）'}], extras:[{v:'mon_w_metal_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_w_org_class', label: '有机污染物-类别测定', items: [{v:'volatile_phenol',l:'挥发酚类'},{v:'benzamine',l:'苯氨类'},{v:'aox',l:'可吸附有机卤素（AOX）'},{v:'tox',l:'总有机卤化物（TOX）'},{v:'oil',l:'石油类'},{v:'organic_matter',l:'有机质'}], extras:[{v:'mon_w_org_c_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_w_org_voc', label: '有机污染物-挥发性和半挥发性', items: [{v:'voc',l:'挥发性有机物'},{v:'svoc',l:'半挥发性有机物'}], extras:[{v:'mon_w_org_v_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_w_org_spec', label: '有机污染物-特定污染物测定', items: [{v:'benzene_org',l:'苯系有机物'},{v:'volatile_halide',l:'挥发性卤代烃'},{v:'phenol_comp',l:'酚类化合物'},{v:'chlorobenzene',l:'氯苯类化合物'},{v:'aniline',l:'苯胺类化合物'},{v:'nitrobenzene',l:'硝基苯类化合物'},{v:'formaldehyde',l:'甲醛'},{v:'organochlorine',l:'有机氯农药'},{v:'organophosphorus',l:'有机磷农药'},{v:'atrazine',l:'阿特拉津'},{v:'acrylonitrile',l:'丙烯腈和丙烯醛'},{v:'trichloroacetaldehyde',l:'三滤乙醛'},{v:'pah',l:'多环芳烃'},{v:'dioxin',l:'二噁英类'},{v:'pcb',l:'多氯联苯'},{v:'organotin',l:'有机锡化物'},{v:'anionic_det',l:'阴离子洗涤剂'}], extras:[{v:'mon_w_org_s_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_w_bio', label: '生物监测', items: [{v:'plankton',l:'浮游生物'},{v:'benthos',l:'底栖生物'},{v:'primary_prod',l:'初级生产力测定'},{v:'bacteria_total',l:'细菌总数'},{v:'total_coliform',l:'总大肠杆菌'},{v:'fecal_coliform',l:'粪大肠杆菌、沙门氏菌'}], extras:[{v:'mon_w_bio_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_w_auto', label: '水质自动监测系统', items: [{v:'auto_ph',l:'pH（氢离子浓度指数）'},{v:'auto_cond',l:'电导率'},{v:'auto_do',l:'溶解氧（DO）'},{v:'auto_turb',l:'浊度'},{v:'auto_temp',l:'温度'},{v:'auto_cod',l:'化学需氧量'},{v:'auto_codmn',l:'高锰酸盐指数'},{v:'auto_toc',l:'总有机碳'},{v:'auto_oil',l:'石油类'},{v:'auto_cn',l:'氰化物'},{v:'auto_as',l:'砷'},{v:'auto_cr6',l:'六价铬'},{v:'auto_pb',l:'铅'},{v:'auto_cd',l:'镉'},{v:'auto_nh3n',l:'氨氮'},{v:'auto_tn',l:'总氮'},{v:'auto_tp',l:'总磷'},{v:'auto_do2',l:'溶解氧'},{v:'auto_flow',l:'污水流量'}], extras:[{v:'mon_w_auto_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_w_sediment', label: '底质监测', items: [] }
  ] },
  air: { name: '大气污染治理', type: 'grouped', groups: [
    { id: 'mon_a_phys', label: '综合指标-理化指标', items: [{v:'a_temp',l:'温度'},{v:'a_pressure',l:'压力'},{v:'a_speed',l:'流速'},{v:'a_humidity',l:'湿度'},{v:'a_o2',l:'烟气含氧量'},{v:'a_blackness',l:'烟气黑度'}], extras:[{v:'mon_a_phys_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_a_gas', label: '综合指标-气态污染物', items: [{v:'a_so2',l:'二氧化硫（SO2）'},{v:'a_nox',l:'氮氧化物（NOX）'},{v:'a_pm',l:'颗粒物浓度'},{v:'a_co',l:'一氧化碳（CO）'},{v:'a_co2',l:'二氧化碳（CO2）'},{v:'a_o3',l:'臭氧（O3）'},{v:'a_h2s',l:'硫化氢（H2S）'},{v:'a_hf',l:'氟化氢（HF）'},{v:'a_hcl',l:'氯化氢（HCl）'},{v:'a_nh3',l:'氨（NH3）'},{v:'a_hcn',l:'氰化氢（HCN）'},{v:'a_cl2',l:'氯气（Cl2）'},{v:'a_fluoride',l:'氟化物'}], extras:[{v:'mon_a_gas_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_a_heavy', label: '综合指标-重金属', items: [{v:'a_hg',l:'汞（Hg）'},{v:'a_pb',l:'铅（Pb）'},{v:'a_cd',l:'镉（Cd）'},{v:'a_cr',l:'铬（Cr）'},{v:'a_as',l:'砷（As）'}], extras:[{v:'mon_a_heavy_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_a_org_class', label: '有机污染物-类别测定', items: [{v:'a_tvoc',l:'总挥发性有机物（TVOC）'},{v:'a_nmhc',l:'非甲烷总烃'},{v:'a_vhc',l:'挥发性卤代烃'},{v:'a_phenol',l:'酚类化合物'},{v:'a_aldehyde',l:'醛酮类化合物'},{v:'a_pah',l:'多环芳烃'},{v:'a_dioxin',l:'二噁英类'},{v:'a_pcb',l:'多氯联苯'}], extras:[{v:'mon_a_org_c_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_a_org_voc', label: '有机污染物-挥发性和半挥发性', items: [{v:'a_voc',l:'挥发性有机物'},{v:'a_svoc',l:'半挥发性有机物'}], extras:[{v:'mon_a_org_v_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_a_org_spec', label: '有机污染物-特定污染物测定', items: [{v:'a_benzene',l:'苯'},{v:'a_toluene',l:'甲苯'},{v:'a_xylene',l:'二甲苯'},{v:'a_ethylbenzene',l:'乙苯'},{v:'a_styrene',l:'苯乙烯'},{v:'a_formaldehyde',l:'甲醛'},{v:'a_acetaldehyde',l:'乙醛'},{v:'a_acrolein',l:'丙烯醛'},{v:'a_vinyl_cl',l:'氯乙烯'},{v:'a_tce',l:'三氯乙烯'},{v:'a_pce',l:'四氯乙烯'},{v:'a_chloroform',l:'三氯甲烷'},{v:'a_ccl4',l:'四氯化碳'}], extras:[{v:'mon_a_org_s_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_a_bio', label: '生物监测', items: [{v:'a_microbe',l:'大气微生物总数'},{v:'a_bacteria_aero',l:'细菌气溶胶'},{v:'a_fungi_aero',l:'真菌气溶胶'},{v:'a_pollen',l:'花粉过敏原'}], extras:[{v:'mon_a_bio_o',l:'其他',ph:'请填写'}] }
  ] },
  water_eco: { name: '水生态修复', type: 'grouped', groups: [
    { id: 'mon_eco_phys', label: '综合指标-理化指标', items: [{v:'eco_w_temp',l:'水温'},{v:'eco_color',l:'色度'},{v:'eco_odor',l:'臭'},{v:'eco_turb',l:'浊度'},{v:'eco_trans',l:'透明度'},{v:'eco_ph',l:'pH'},{v:'eco_residue',l:'残渣'},{v:'eco_mineral',l:'矿化度'},{v:'eco_cond',l:'电导率'},{v:'eco_redox',l:'氧化还原电位'},{v:'eco_acid',l:'酸度'},{v:'eco_alka',l:'碱度'},{v:'eco_co2',l:'二氧化碳'}], extras:[{v:'mon_eco_phys_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_eco_anion', label: '综合指标-无机阴离子', items: [{v:'eco_sulfide',l:'硫化物'},{v:'eco_cyanide',l:'氰化物'},{v:'eco_sulfate',l:'硫酸盐'},{v:'eco_boron',l:'硼'},{v:'eco_cl_free',l:'游离氯和总氯'},{v:'eco_chloride',l:'氯化物'},{v:'eco_fluoride',l:'氟化物'},{v:'eco_iodide',l:'碘化物'}] },
    { id: 'mon_eco_nutrient', label: '综合指标-营养盐及有机污染综合指标', items: [{v:'eco_do',l:'溶解氧'},{v:'eco_cod',l:'化学需氧量'},{v:'eco_codmn',l:'高锰酸盐指数'},{v:'eco_bod',l:'生化需氧量'},{v:'eco_toc',l:'总有机碳'},{v:'eco_p_el',l:'元素磷'},{v:'eco_p',l:'磷'},{v:'eco_kjn',l:'凯氏氮'},{v:'eco_tn',l:'总氮'},{v:'eco_no3n',l:'硝酸盐氮'},{v:'eco_no2n',l:'亚硝酸盐氮'},{v:'eco_nh3n',l:'氨氮'}], extras:[{v:'mon_eco_nutr_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_eco_metal', label: '综合指标-金属及其化合物', items: [{v:'eco_ag',l:'银'},{v:'eco_al',l:'铝'},{v:'eco_as',l:'砷'},{v:'eco_ba',l:'钡'},{v:'eco_be',l:'铍'},{v:'eco_bi',l:'铋'},{v:'eco_cd',l:'镉'},{v:'eco_co',l:'钴'},{v:'eco_cr',l:'铬'},{v:'eco_cu',l:'铜'},{v:'eco_hg',l:'汞'},{v:'eco_fe',l:'铁'},{v:'eco_mn',l:'锰'},{v:'eco_ni',l:'镍'},{v:'eco_mo',l:'钼'},{v:'eco_pb',l:'铅'},{v:'eco_sb',l:'锑'},{v:'eco_se',l:'硒'},{v:'eco_zn',l:'锌'},{v:'eco_v',l:'钒'},{v:'eco_in_tl',l:'铟和铊'},{v:'eco_th',l:'钍'},{v:'eco_u',l:'铀'},{v:'eco_k_na',l:'钾和钠'},{v:'eco_ca_mg',l:'钙、镁（含总硬度）'}], extras:[{v:'mon_eco_metal_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_eco_org_class', label: '有机污染物-类别测定', items: [{v:'eco_phenol',l:'挥发酚类'},{v:'eco_benzamine',l:'苯氨类'},{v:'eco_nitrobenz',l:'硝基苯类'},{v:'eco_aox',l:'可吸附有机卤素（AOX）'},{v:'eco_tox',l:'总有机卤化物（TOX）'},{v:'eco_oil',l:'石油类'},{v:'eco_org',l:'有机质'}], extras:[{v:'mon_eco_org_c_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_eco_org_voc', label: '有机污染物-挥发性和半挥发性', items: [{v:'eco_voc',l:'挥发性有机物'},{v:'eco_svoc',l:'半挥发性有机物'}], extras:[{v:'mon_eco_org_v_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_eco_org_spec', label: '有机污染物-特定污染物测定', items: [{v:'eco_benzene_org',l:'苯系有机物'},{v:'eco_vhc',l:'挥发性卤代烃'},{v:'eco_phenol_c',l:'酚类化合物'},{v:'eco_clbenz',l:'氯苯类化合物'},{v:'eco_aniline',l:'苯胺类化合物'},{v:'eco_nitrobenz_c',l:'硝基苯类化合物'},{v:'eco_phthalate',l:'邻苯二甲酸类'},{v:'eco_formaldehyde',l:'甲醛'},{v:'eco_orgcl',l:'有机氯农药'},{v:'eco_orgp',l:'有机磷农药'},{v:'eco_atrazine',l:'阿特拉津'},{v:'eco_acrylo',l:'丙烯腈和丙烯醛'},{v:'eco_tcaa',l:'三滤乙醛'},{v:'eco_pah',l:'多环芳烃'},{v:'eco_dioxin',l:'二噁英类'},{v:'eco_pcb',l:'多氯联苯'},{v:'eco_orgtin',l:'有机锡化物'},{v:'eco_anionic',l:'阴离子洗涤剂'}], extras:[{v:'mon_eco_org_s_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_eco_bio', label: '生物监测', items: [{v:'eco_plankton',l:'浮游生物'},{v:'eco_benthos',l:'底栖生物'},{v:'eco_animal',l:'动物'},{v:'eco_plant',l:'植物'},{v:'eco_primary',l:'初级生产力测定'},{v:'eco_bacteria',l:'细菌总数'},{v:'eco_coliform',l:'总大肠杆菌'},{v:'eco_fecal',l:'粪大肠杆菌、沙门氏菌'},{v:'eco_strep',l:'粪链球菌'}] },
    { id: 'mon_eco_auto', label: '水质自动监测系统', items: [{v:'eco_a_ph',l:'pH（氢离子浓度指数）'},{v:'eco_a_cond',l:'电导率'},{v:'eco_a_do',l:'溶解氧（DO）'},{v:'eco_a_turb',l:'浊度'},{v:'eco_a_temp',l:'温度'},{v:'eco_a_cod',l:'化学需氧量'},{v:'eco_a_codmn',l:'高锰酸盐指数'},{v:'eco_a_toc',l:'总有机碳'},{v:'eco_a_oil',l:'石油类'},{v:'eco_a_cn',l:'氰化物'},{v:'eco_a_as',l:'砷'},{v:'eco_a_cr6',l:'六价铬'},{v:'eco_a_pb',l:'铅'},{v:'eco_a_cd',l:'镉'},{v:'eco_a_nh3n',l:'氨氮'},{v:'eco_a_tn',l:'总氮'},{v:'eco_a_tp',l:'总磷'},{v:'eco_a_do2',l:'溶解氧'},{v:'eco_a_flow',l:'污水流量'}], extras:[{v:'mon_eco_auto_o',l:'其他',ph:'请填写'}] },
    { id: 'mon_eco_sediment', label: '底质监测', items: [{v:'eco_sed_dist',l:'低质扰动'},{v:'eco_sed_nutr',l:'营养盐释放'}] },
    { id: 'mon_eco_atm', label: '大气监测', items: [{v:'eco_atm_pm25',l:'PM2.5'},{v:'eco_atm_pm10',l:'PM₁₀'},{v:'eco_atm_so2',l:'SO₂'},{v:'eco_atm_no2',l:'NO₂'},{v:'eco_atm_co',l:'CO'},{v:'eco_atm_o3',l:'O₃'},{v:'eco_atm_vocs',l:'VOCs'},{v:'eco_atm_nh3',l:'NH₃'},{v:'eco_atm_ch4',l:'CH4'},{v:'eco_atm_co2',l:'CO2'},{v:'eco_atm_neg_ion',l:'负离子'}], extras:[{v:'mon_eco_atm_o',l:'其他',ph:'请填写'}] }
  ] },
  other: { name: '其他', type: 'textarea' }
}
